services:
  db:
    ports:
      - "${DB_PORT}:5432"
  
  backend:
    build:
      target: dev
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${DOZZLE_PORT}:8080"
    networks:
      - app_net
    environment:
      - DOZZLE_LEVEL=${DOZZLE_LEVEL}